### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by luaxlab** [SamboyCoding/OpenTKAvalonia#4]
Greetings
I would like to use this project (or a fork that is more up to date respectively) in an ongoing open-source project of mine.

However, this project is missing a LICENSE.md file, thus making it copyright protected with no permissions whatsoever granted (which I assume, is not the intended purpose).

Could you clarify this, or add a LICENSE.md that grants permission (e.g. MIT, CC, GPL) or explicitly probhits use?

**Comment by SamboyCoding** [comment]
Apologies, I usually license all my work under MIT, but this one slipped that radar. I'll fix this now.
